name: Timeout Example

on: [push]
concurrency:
  group: ${{ github.repository }}-${{ github.ref }}
  cancel-in-progress: true # it will cancel the running one, pickup new one
jobs:
  test-timeout:
    runs-on: ubuntu-latest
    timeout-minutes: 5
 
    steps:
      - name: Start job
        run: echo "This job will timeout if it runs longer than 5 minutes."

      - name: Simulate long running task
        run: |
          echo "Sleeping for 10 minutes..."
          sleep 600